#!/bin/bash

set -eo pipefail
shopt -s inherit_errexit nullglob

# bumps form-js dependencies in bpmn-io-demo

PWD="$(pwd)"
WORKDIR="$(pwd)/tmp"
CLONE_DIR="$WORKDIR/bpmn-io-demo"

# create work dir
mkdir -p "$WORKDIR"

git clone --depth=1 "https://$BPMN_IO_TOKEN@github.com/$BPMN_IO_DEMO_ENDPOINT.git" "$CLONE_DIR"

cd "$CLONE_DIR"

npm install --save @bpmn-io/form-js@$TAG diagram-js@latest

if [[ "x$SKIP_COMMIT" = "x" ]]; then

  git config user.email "$BPMN_IO_EMAIL"
  git config user.name "$BPMN_IO_USERNAME"
  git config push.default simple

  git add -A
  git commit -m "deps: bump to @bpmn-io/form-js@$TAG"
  git tag "form-js-$TAG"
  git push -q &2>/dev/null
  git push --tags -q &2>/dev/null
else
  echo "Skipping commit (SKIP_COMMIT=$SKIP_COMMIT)"
fi

cd "$PWD"