name: Add to HTO project

on:
  issues:
    types:
      - opened
      - transferred
  pull_request:
    types:
      - opened

jobs:
  Exec:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@c3dbb76ad4e3cf259aa2ae775c8931d4a840251f
        with:
          project-url: ${{ secrets.HTO_PROJECT_URL }}
          github-token: ${{ secrets.ADD_TO_HTO_PROJECT_PAT }}
