name: Add to HTO project

on:
  issues:
    types:
      - opened
      - transferred
  pull_request:
    types:
      - opened

jobs:
  Exec:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@097fa0553b3e9b086707f31c11ac80cad560f757
        with:
          project-url: ${{ secrets.HTO_PROJECT_URL }}
          github-token: ${{ secrets.ADD_TO_HTO_PROJECT_PAT }}
