name: Add to HTO project

on:
  issues:
    types:
      - opened
      - transferred
  pull_request:
    types:
      - opened

jobs:
  Exec:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@5ba1147d0e730433604387e30a57a6079f51a893
        with:
          project-url: ${{ secrets.HTO_PROJECT_URL }}
          github-token: ${{ secrets.ADD_TO_HTO_PROJECT_PAT }}
