name: Merge develop to v2
on:
  push:
    branches:
      - 'develop'

jobs:
  Merge_main_to_develop:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout v2 branch
        uses: actions/checkout@v4
        with:
          ref: v2
          fetch-depth: 0
      - name: Merge develop to v2 and push
        run: |
          git config user.name '${{ secrets.BPMN_IO_USERNAME }}'
          git config user.email '${{ secrets.BPMN_IO_EMAIL }}'
          git merge -m 'Merge develop to v2' --no-edit origin/develop
          git push

      - name: Notify failure on Slack
        if: failure()
        uses: slackapi/slack-github-action@v1.15.0
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          slack-message: 'Automatic merge of <https://github.com/${{ github.repository }}/tree/${{ github.ref }}|${{ github.ref }}> to <https://github.com/${{ github.repository }}/tree/v2|${{ github.repository }}#v2> failed.'
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
