name: Update Visual Regression Snapshots

on:
  pull_request:
    types: [labeled, synchronize]

jobs:
  update-snapshots:
    if: github.event.pull_request.state != 'closed' && (github.event.label.name == 'update-snapshots' || contains( github.event.pull_request.labels.*.name, 'update-snapshots'))
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.51.1
      options: --user 1001:1000

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup NPM cache
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install node dependencies
        run: npm ci
      - name: Build frontend
        run: npm run build
      - name: Build mock website
        run: npm run build:e2e
      - name: Start server
        run: npm run start:visual-preview
      - name: Run Playwright tests
        run: npm run test:visual -- --update-snapshots
      - name: Commit screenshots
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: 'chore: updated snapshots'
