name: Update Visual Regression Snapshots

on:
  pull_request:
    types: [labeled, synchronize]

jobs:
  update-snapshots:
    if: github.event.pull_request.state != 'closed' && (github.event.label.name == 'deploy-preview' || contains( github.event.pull_request.labels.*.name, 'deploy-preview'))
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.41.0
      options: --user 1001:1000

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4
    - name: Setup NPM cache
      uses: actions/setup-node@v4
      with:
        node-version: "20"
        cache: "npm"
    - name: Install node dependencies
      run: npm ci
    - name: Build frontend
      run: npm run build
    - name: Build mock website
      run: npm run build:e2e
    - name: Start server
      run: npm run start:visual-preview
    - name: Run Playwright tests
      run: npm run test:visual -- --update-snapshots
    - name: Overwrite Playwright snapshots
      run: |
          git config user.name '${{ secrets.BPMN_IO_USERNAME }}'
          git config user.email '${{ secrets.BPMN_IO_EMAIL }}'
          git add -A
          git commit -m "chore(CI): updated snapshots" || echo "No changes to commit"
          git push
