name: Visual regression tests
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.39.0
      options: --user 1001:1000
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup NPM cache
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "npm"
      - name: Install node dependencies
        run: npm ci
      - name: Build frontend
        run: npm run build
      - name: Build mock website
        run: npm run build:e2e
      - name: Start server
        run: npm run start:visual-preview
      - name: Run Playwright tests
        if: github.ref != 'refs/heads/develop' && github.ref != 'refs/heads/master'
        run: npm run test:visual
      - name: Overwrite Playwright snapshots
        if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/master'
        run: |
          npm run test:visual -- --update-snapshots
          git config user.name '${{ secrets.BPMN_IO_USERNAME }}'
          git config user.email '${{ secrets.BPMN_IO_EMAIL }}'
          git add -A
          git commit -m "chore(CI): updated snapshots [skip ci]" || echo "No changes to commit"
          git push

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Playwright report
          path: playwright-report/
          retention-days: 30
