name: Visual regression tests
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup NPM cache
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"
      - name: Install node dependencies
        run: npm ci
      - name: Store Playwright's Version
        run: |
          PLAYWRIGHT_VERSION=$(npm ls @playwright/test | grep @playwright | sed 's/.*@//')
          echo "Playwright's Version: $PLAYWRIGHT_VERSION"
          echo "PLAYWRIGHT_VERSION=$PLAYWRIGHT_VERSION" >> $GITHUB_ENV
      - name: Cache Playwright Browsers for Playwright's Version
        id: cache-playwright-browsers
        uses: actions/cache@v3
        with:
          path: ~/.cache/ms-playwright
          key: playwright-browsers-${{ env.PLAYWRIGHT_VERSION }}
      - name: Install playwright browsers
        if: steps.cache-playwright-browsers.outputs.cache-hit != 'true'
        run: npx playwright install --with-deps
      - name: Build frontend
        run: npm run build
      - name: Start server
        run: npm run start:visual-preview
      - name: Run Playwright tests
        run: npm run test:visual
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Playwright report
          path: playwright-report/
          retention-days: 30
